USE `quartz-db` ;

-- -----------------------------------------------------
-- Table `qrtz_job_history`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `qrtz_job_history` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `qrtz_job_history` (
  `ENTRY_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `HOSTNAME` VARCHAR(250) NULL DEFAULT NULL,
  `IP_ADDR` VARCHAR(250) NULL DEFAULT NULL,
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `INSTANCE_NAME` VARCHAR(200) NOT NULL,
  `JOB_NAME` VARCHAR(200) NULL DEFAULT NULL,
  `JOB_GROUP` VARCHAR(200) NULL DEFAULT NULL,
  `TRIGGER_NAME` VARCHAR(200) NOT NULL,
  `TRIGGER_GROUP` VARCHAR(200) NOT NULL,
  `FIRED_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `NEXT_FIRE_TIME` TIMESTAMP NOT NULL,
  `PRIORITY` INT(11) NOT NULL,
  `IS_NONCONCURRENT` TINYINT(1) NULL DEFAULT NULL,
  `REQUESTS_RECOVERY` TINYINT(1) NULL DEFAULT NULL,
  `RESULT` VARCHAR(250) NOT NULL,
  `EXCEPTIONS` VARCHAR(2500) NULL DEFAULT NULL,
  PRIMARY KEY (`ENTRY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- ALTER TABLE `qrtz_job_history`
-- CHANGE COLUMN `NEXT_FIRE_TIME` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00';

SHOW WARNINGS;
